export default themes = [
  {
    id: 0,
    name: "DARK",
    time: "white",
    icon: "white",
    background: "#1c1c1c",
    modal: "black",
    shadow: "black",
    activities: "black",
    tasks: "black",
    button: "black",
    text: "white",
    settingsText: "white",
    accent: "gray",
  },
  {
    id: 1,
    name: "LIGHT",
    time: "black",
    icon: "black",
    background: "white",
    modal: "white",
    shadow: "black",
    activities: "#e8e8e8",
    tasks: "black",
    button: "#e8e8e8",
    text: "black",
    settingsText: "black",
    accent: "gainsboro",
  },
];
