export default themes = [
  {
    name: "DARK",
    time: "white",
    icon: "white",
    background: "black",
    modal: "black",
    shadow: "black",
    activities: "black",
    tasks: "black",
    button: "black",
    text: "white",
  },
  {
    name: "LIGHT",
    time: "black",
    icon: "black",
    background: "white",
    modal: "white",
    shadow: "black",
    activities: "black",
    tasks: "black",
    button: "black",
    text: "white",
  },
];
